### ISSUE TITLE
Why the converter trips off with CSS multiline comment?

### ISSUE THREAD

**Issue by millisami** [jpablobr/css2sass#2]
The CSS to convert to SASS:

``` css
body {
   background: transparent !important; color: #444 !important; text-shadow: none;
  }

  /* Don't show links for images */
  pre, blockquote {
   border: 1px solid #999; page-break-inside: avoid;
  }
  img {
   page-break-inside: avoid;
  }


/* Grade-A Mobile Browsers */
html {
   -webkit-text-size-adjust:none; -ms-text-size-adjust:none;
  }
```

Converted SASS:

``` sass
body
  background: transparent !important
  color: #444 !important
  text-shadow: none

/* Don't show links for images

pre, blockquote
  border: 1px solid #999
  page-break-inside: avoid

img
  page-break-inside: avoid

/* Grade-A Mobile Browsers

html
  -webkit-text-size-adjust: none
  -ms-text-size-adjust: none
```

Watch out the `/* Don't show links for images` and `/* Grade-A Mobile Browsers`.
That makes the whole block after it commented.
It should have been `/* Don't show links for images */` instead?
