### ISSUE TITLE
Incorrect conversion

### ISSUE THREAD

**Issue by CasEbb** [jpablobr/css2sass#8]
``` css
.preamble {
/*  color: #FF0045;*/
  font-weight: bold;
  margin-bottom: 12px;
  overflow: hidden;
}

.regularPage .preamble p {
  color: #FF0045;
  margin: 0 0 2px;
  font-size: 11pt;
  font-weight: normal;
}
```

Converts to:

``` sass
.preamble
  /*  color: #FF0045;
  font-weight: bold
  margin-bottom: 12px
  overflow: hidden

.regularPage p
  color: #FF0045
  margin: 0 0 2px
  font-size: 11pt
  font-weight: normal
```
